sudo: false
language: node_js
node_js:
  - v5.7
  - v5.6
  - v5.5
  - v4.3
env:
- NODE_ENV=development
notifications:
  slack:
    secure: Ab++IL6ZS4IniRq4AkI6y28wBIynI0jep6UqXgIpmmJxegDwRca+/E8XzyzxSBtuxKZh1BECX4R4U6A59TyCFzGVD9wsb+W25al3IZBCaBhKyKFqs6TA9NAsnRyvl2wE1O85y9KULRZcp3ko12xQjeUBqlSgsPwmfKAVxMG9x7k=
deploy:
  provider: npm
  email: kyan.ql.he@gmail.com
  api_key:
    secure: T1ZWXN77LIhmaGr8JIQk/jW50Q1FksQBEIoYvIfG1oJyc/ynEbWSikCXRazJaj/bNmamo9Pjtyp/5ssuoPYgyPbbGwEeZDmtLWsUQkWbPP5haUIZUoYTDZTlcB37JWNOcra+a0LFsa3m+A708FeTONsXaGmQcC0jmZU2bXOlHcs=
  on:
    tags: true
    repo: cybertk/ramlev
